// React/film-review/src/components/AddFilm.jsx
import React, { useState } from 'react';
import axios from 'axios';

const AddFilm = () => {
  const [formData, setFormData] = useState({
    title: '',
    director: '',
    year: '',
    imageUrl: '',
    rating: ''
  });

  const handleChange = e => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = e => {
    e.preventDefault();
    axios.post('http://localhost:4500/films', formData)
      .then(response => {
        console.log('Film added:', response.data);
        alert('Film added successfully!');
        setFormData({ title: '', director: '', year: '', imageUrl: '', rating: '' });
      })
      .catch(error => console.error('Error adding film:', error));
  };

return (
    <div className="container">
        <h2>Add New Film</h2>
        <form onSubmit={handleSubmit}>
            <div className="form-group">
                <label htmlFor="title">Title</label>
                <input
                    id="title"
                    className="form-control"
                    name="title"
                    value={formData.title}
                    onChange={handleChange}
                    required
                />
            </div>
            <div className="form-group">
                <label htmlFor="director">Director</label>
                <input
                    id="director"
                    className="form-control"
                    name="director"
                    value={formData.director}
                    onChange={handleChange}
                    required
                />
            </div>
            <div className="form-group">
                <label htmlFor="year">Year</label>
                <input
                    id="year"
                    className="form-control"
                    type="number"
                    name="year"
                    value={formData.year}
                    onChange={handleChange}
                    required
                />
            </div>
            <div className="form-group">
                <label htmlFor="imageUrl">Image URL</label>
                <input
                    id="imageUrl"
                    className="form-control"
                    name="imageUrl"
                    value={formData.imageUrl}
                    onChange={handleChange}
                    required
                />
            </div>
            <div className="form-group">
                <label htmlFor="rating">Rating</label>
                <select
                    id="rating"
                    className="form-control"
                    name="rating"
                    value={formData.rating}
                    onChange={handleChange}
                    required
                >
                    <option value="">Select Rating</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <button type="submit" className="btn btn-primary">Add Film</button>
        </form>
    </div>
);
};

export default AddFilm;

// Angular/angular-handson/src/app/add-film/add-film.component.ts
import { Component } from '@angular/core';
import { FilmService } from '../services/film.service';
import { Film } from '../models/film';

@Component({
  selector: 'app-add-film',
  templateUrl: './add-film.component.html',
  styleUrls: ['./add-film.component.css']
})
export class AddFilmComponent {
  title: string;
  director: string;
  year: number;
  imageUrl: string;
  rating: number;

  constructor(private filmService: FilmService) {
    this.title = '';
    this.director = '';
    this.year = NaN;
    this.imageUrl = '';
    this.rating = NaN;
  }

  onSubmit(): void {
    const film: Film = { id: Date.now(), title: this.title, director: this.director, year: this.year, imageUrl: this.imageUrl, rating: this.rating };
    this.filmService.addFilm(film).subscribe();
    this.title = '';
    this.director = '';
    this.year = NaN;
    this.imageUrl = '';
    this.rating = NaN;

  }
}

<div class="container">
  <h2>Add New Film</h2>
  <form (ngSubmit)="onSubmit()">
    <div class="form-group">
      <label for="title">Title</label>
      <input [(ngModel)]="title" name="title" class="form-control" required>
    </div>
    <div class="form-group">
      <label for="director">Director</label>
      <input [(ngModel)]="director" name="director" class="form-control" required>
    </div>
    <div class="form-group">
      <label for="year">Year</label>
      <input [(ngModel)]="year" name="year" type="number" class="form-control" required>
    </div>
    <div class="form-group">
      <label for="imageUrl">Image URL</label>
      <input [(ngModel)]="imageUrl" name="imageUrl" class="form-control" required>
    </div>
    <div class="form-group">
      <label for="rating">Rating</label>
      <select [(ngModel)]="rating" name="rating" class="form-control" required>
        <option [value]="1">1</option>
        <option [value]="2">2</option>
        <option [value]="3">3</option>
        <option [value]="4">4</option>
        <option [value]="5">5</option>
      </select>
    </div>
    <button type="submit" class="btn btn-primary">Add Film</button>
  </form>
</div>
