// React/film-review/src/components/FilmItem.jsx
import React from 'react';

const FilmItem = ({ film }) => {
  return (
    <div className="card mb-3">
      <div className="row g-0">
        <div className="col-md-4">
          <img src={film.imageUrl} className="img-fluid rounded-start" alt={film.title} />
        </div>
        <div className="col-md-8">
          <div className="card-body">
            <h5 className="card-title">{film.title}</h5>
            <p className="card-text">Directed by: {film.director}</p>
            <p className="card-text">Year: {film.year}</p>
            <p className="card-text">Rating: {film.rating}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FilmItem;

// Weekly Tasks/angular-handson/src/app/film-item/film-item.component.ts
import { Component, Input } from '@angular/core';
import { Film } from '../models/film';

@Component({
  selector: 'app-film-item',
  templateUrl: './film-item.component.html',
  styleUrls: ['./film-item.component.css']
})
export class FilmItemComponent {
  @Input() film: Film;

  constructor() {
    this.film = { id: 0, title: '', director: '', year: NaN, imageUrl: '' , rating: NaN};
  }
}

<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <img [src]="film.imageUrl" class="img-fluid rounded-start" alt="{{ film.title }}">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ film.title }}</h5>
        <p class="card-text">Directed by: {{ film.director }}</p>
        <p class="card-text">Year: {{ film.year }}</p>
        <p class="card-text">Rating: {{ film.rating }}</p>
      </div>
    </div>
  </div>
</div>
